import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { analyzeDiff } from "./diff.js";
import { detectProject } from "./detect.js";
import { listTopLevelDirs } from "./repo-stats.js";
import type { CategoryKey } from "./types.js";

const GENERATED_MARKER = "<!-- Generated by comp-gate init; edit for accuracy -->";

const DIR_ROLES: Record<string, string> = {
  src: "application source",
  lib: "library source",
  apps: "applications",
  packages: "shared packages",
  services: "services",
  tests: "test suites",
  test: "tests",
  docs: "documentation",
  scripts: "utility scripts",
  cmd: "command-line entrypoints",
  internal: "internal packages",
  api: "API layer",
  web: "web frontend",
  server: "server code",
  infra: "infrastructure",
  terraform: "infrastructure as code",
  migrations: "database migrations",
  models: "data models",
  components: "UI components",
};

function readText(filePath: string): string {
  if (!existsSync(filePath)) {
    return "";
  }
  return readFileSync(filePath, "utf8");
}

function firstParagraph(text: string, maxLen = 200): string | null {
  const lines = text.split("\n");
  const parts: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      if (parts.length > 0) {
        break;
      }
      continue;
    }
    parts.push(trimmed);
    if (parts.join(" ").length >= maxLen) {
      break;
    }
  }

  if (parts.length === 0) {
    return null;
  }

  const paragraph = parts.join(" ");
  return paragraph.length > maxLen ? `${paragraph.slice(0, maxLen - 3)}...` : paragraph;
}

interface StackInfo {
  language: string;
  framework: string;
  runtime: string;
}

function inferStack(cwd: string): StackInfo {
  const stack: StackInfo = {
    language: "Unknown",
    framework: "Unknown",
    runtime: "Unknown",
  };

  const packageJsonPath = path.join(cwd, "package.json");
  if (existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(readText(packageJsonPath)) as {
        name?: string;
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
        engines?: { node?: string };
      };
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      stack.language = "TypeScript/JavaScript";
      stack.runtime = pkg.engines?.node ? `Node.js ${pkg.engines.node}` : "Node.js";

      if (deps.react) {
        stack.framework = "React";
      } else if (deps.vue) {
        stack.framework = "Vue";
      } else if (deps.svelte) {
        stack.framework = "Svelte";
      } else if (deps.next) {
        stack.framework = "Next.js";
      } else if (deps.express) {
        stack.framework = "Express";
      } else if (deps.fastify) {
        stack.framework = "Fastify";
      } else if (deps.nestjs || deps["@nestjs/core"]) {
        stack.framework = "NestJS";
      } else if (pkg.name) {
        stack.framework = pkg.name;
      }
    } catch {
      stack.language = "JavaScript";
    }
    return stack;
  }

  if (existsSync(path.join(cwd, "pyproject.toml"))) {
    stack.language = "Python";
    const pyproject = readText(path.join(cwd, "pyproject.toml"));
    if (/fastapi/i.test(pyproject)) {
      stack.framework = "FastAPI";
    } else if (/django/i.test(pyproject)) {
      stack.framework = "Django";
    } else if (/flask/i.test(pyproject)) {
      stack.framework = "Flask";
    }
    return stack;
  }

  if (existsSync(path.join(cwd, "go.mod"))) {
    stack.language = "Go";
    const goMod = readText(path.join(cwd, "go.mod"));
    if (/gin\b/i.test(goMod)) {
      stack.framework = "Gin";
    } else if (/echo\b/i.test(goMod)) {
      stack.framework = "Echo";
    }
    return stack;
  }

  if (existsSync(path.join(cwd, "Cargo.toml"))) {
    stack.language = "Rust";
    return stack;
  }

  return stack;
}

function architectureLines(cwd: string): string[] {
  const dirs = listTopLevelDirs(cwd);
  if (dirs.length === 0) {
    return ["- Add top-level directories and their roles here."];
  }

  return dirs.map((dir) => {
    const role = DIR_ROLES[dir.toLowerCase()] ?? "project directory";
    return `- \`${dir}/\` — ${role}`;
  });
}

function conventionsLine(cwd: string): string {
  const contributing = readText(path.join(cwd, "CONTRIBUTING.md"));
  const readme = readText(path.join(cwd, "README.md"));

  const snippet = firstParagraph(contributing) ?? firstParagraph(readme);
  if (snippet) {
    return snippet;
  }

  return "Follow existing naming and import patterns in each directory.";
}

function runtimeLines(cwd: string): string[] {
  const packageJsonPath = path.join(cwd, "package.json");
  if (existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(readText(packageJsonPath)) as { scripts?: Record<string, string> };
      const scripts = pkg.scripts ?? {};
      const lines: string[] = [];

      const runLocal = scripts.dev ?? scripts.start ?? scripts.serve;
      if (runLocal) {
        lines.push(`- How to run locally: \`npm run ${scripts.dev ? "dev" : scripts.start ? "start" : "serve"}\``);
      } else {
        lines.push("- How to run locally:");
      }

      if (scripts.test) {
        lines.push("- How to run tests: `npm test`");
      } else {
        lines.push("- How to run tests:");
      }

      if (scripts.build) {
        lines.push(`- Build: \`npm run build\``);
      }

      return lines;
    } catch {
      // fall through
    }
  }

  const makefile = readText(path.join(cwd, "Makefile"));
  if (makefile) {
    const lines: string[] = [];
    if (/^test:/m.test(makefile)) {
      lines.push("- How to run tests: `make test`");
    } else {
      lines.push("- How to run tests:");
    }
    if (/^(run|dev|start):/m.test(makefile)) {
      lines.push("- How to run locally: `make run` (or `make dev`)");
    } else {
      lines.push("- How to run locally:");
    }
    return lines;
  }

  return ["- How to run locally:", "- How to run tests:"];
}

const CATEGORY_LABELS: Partial<Record<CategoryKey, string>> = {
  frontend: "frontend",
  backend: "backend",
  machineLearning: "machine learning",
  cybersecurity: "cybersecurity",
  devops: "devops",
  mobile: "mobile",
  dataEngineering: "data engineering",
  database: "database",
  testing: "testing",
};

function domainLines(cwd: string): string[] {
  const analysis = analyzeDiff(cwd);
  const detection = detectProject(cwd, analysis);

  const enabled = Object.entries(detection.suggestedCategories)
    .filter(([, suggestion]) => suggestion.enabled && suggestion.confidence >= 0.8)
    .map(([key]) => CATEGORY_LABELS[key as CategoryKey] ?? key)
    .filter(Boolean);

  const primary = enabled[0] ?? "general application development";
  const focus = enabled.slice(1, 4);

  const lines = [`- Primary: ${primary}`];
  if (focus.length > 0) {
    lines.push(`- Focus areas: ${focus.join(", ")}`);
  } else {
    lines.push("- Focus areas:");
  }

  return lines;
}

export function bootstrapSummary(cwd: string): string {
  const stack = inferStack(cwd);
  const arch = architectureLines(cwd);
  const conventions = conventionsLine(cwd);
  const runtime = runtimeLines(cwd);
  const domain = domainLines(cwd);

  return `${GENERATED_MARKER}

# Project Summary

Keep this file updated when architecture, stack, or major conventions change — not on every commit.

## Stack

- Language: ${stack.language}
- Framework: ${stack.framework}
- Runtime: ${stack.runtime}

## Architecture

${arch.join("\n")}

## Conventions

- ${conventions}
- Prefer small, focused modules over large catch-all files.

## Runtime Notes

${runtime.join("\n")}

## Domain

${domain.join("\n")}
`;
}
