import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { bootstrapSummary } from "./bootstrap-summary.js";

describe("bootstrapSummary", () => {
  let tempDir: string;

  afterEach(() => {
    if (tempDir && existsSync(tempDir)) {
      rmSync(tempDir, { recursive: true, force: true });
    }
  });

  it("generates SUMMARY.md from package.json and top-level dirs", () => {
    tempDir = mkdtempSync(path.join(tmpdir(), "testme-bootstrap-"));
    mkdirSync(path.join(tempDir, "src"));
    writeFileSync(
      path.join(tempDir, "package.json"),
      JSON.stringify(
        {
          name: "demo-app",
          scripts: { dev: "vite", test: "vitest run", build: "vite build" },
          dependencies: { react: "^19.0.0", express: "^5.0.0" },
          engines: { node: ">=18" },
        },
        null,
        2,
      ),
      "utf8",
    );
    writeFileSync(path.join(tempDir, "README.md"), "# Demo\n\nA sample React API project.\n", "utf8");

    const summary = bootstrapSummary(tempDir);

    expect(summary).toContain("Generated by comp-gate init");
    expect(summary).toContain("## Stack");
    expect(summary).toContain("TypeScript/JavaScript");
    expect(summary).toContain("React");
    expect(summary).toContain("`src/`");
    expect(summary).toContain("npm run dev");
    expect(summary).toContain("npm test");
    expect(summary).toContain("## Domain");
  });

  it("falls back to template-like defaults for empty repos", () => {
    tempDir = mkdtempSync(path.join(tmpdir(), "testme-bootstrap-"));

    const summary = bootstrapSummary(tempDir);

    expect(summary).toContain("## Stack");
    expect(summary).toContain("Unknown");
    expect(summary).toContain("Add top-level directories");
  });
});
